### ISSUE TITLE
cannot  setup.py install 

### ISSUE THREAD

**Issue by jianrong0520** [theislab/scarches#210]
/home/jianrong/miniconda3/envs/py3.8/bin/python setup.py install
WARNING:root:In order to use the mouse gastrulation seqFISH datsets, please install squidpy (see https://github.com/scverse/squidpy).
/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/scvi_tools-1.0.3-py3.8.egg/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/scvi_tools-1.0.3-py3.8.egg/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from scarches import __author__, __email__, __version__
  File "/home/jianrong/biosoft/scarches/scarches/__init__.py", line 1, in <module>
    from . import dataset, metrics, trainers, models, zenodo, plotting, utils, classifiers
  File "/home/jianrong/biosoft/scarches/scarches/models/__init__.py", line 1, in <module>
    from .trvae.trvae import trVAE
  File "/home/jianrong/biosoft/scarches/scarches/models/trvae/trvae.py", line 9, in <module>
    from .losses import mse, mmd, zinb, nb
  File "/home/jianrong/biosoft/scarches/scarches/models/trvae/losses.py", line 1, in <module>
    from scvi.distributions import NegativeBinomial
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/scvi_tools-1.0.3-py3.8.egg/scvi/__init__.py", line 11, in <module>
    from . import autotune, data, model, external, utils, criticism
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/scvi_tools-1.0.3-py3.8.egg/scvi/autotune/__init__.py", line 1, in <module>
    from ._manager import TuneAnalysis, TunerManager
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/scvi_tools-1.0.3-py3.8.egg/scvi/autotune/_manager.py", line 11, in <module>
    from chex import dataclass
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/chex-0.1.8-py3.8.egg/chex/__init__.py", line 17, in <module>
    from chex._src.asserts import assert_axis_dimension
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/chex-0.1.8-py3.8.egg/chex/_src/asserts.py", line 26, in <module>
    from chex._src import asserts_internal as _ai
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/chex-0.1.8-py3.8.egg/chex/_src/asserts_internal.py", line 34, in <module>
    from chex._src import pytypes
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/chex-0.1.8-py3.8.egg/chex/_src/pytypes.py", line 19, in <module>
    import jax
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/jax-0.4.14-py3.8.egg/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/jax-0.4.14-py3.8.egg/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/jax-0.4.14-py3.8.egg/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/jianrong/miniconda3/envs/py3.8/lib/python3.8/site-packages/jax-0.4.14-py3.8.egg/jax/_src/lib/__init__.py", line 44, in <module>
    minimum_jaxlib_version: str) -> tuple[int, ...]:
TypeError: 'type' object is not subscriptable

**Comment by Koncopd** [comment]
Hi, @jianrong0520 jax probably dropped support of python 3.8, you will need to try with 3.9 at least.

**Comment by jianrong0520** [comment]
Thanks, I would like to try it.

**Comment by erzakiev** [comment]
> Hi, @jianrong0520 jax probably dropped support of python 3.8, you will need to try with 3.9 at least.

the official docs suggest using 3.7 or 3.8 though... confusion
<img width="1072" alt="Screenshot 2024-06-05 at 15 22 56" src="https://github.com/theislab/scarches/assets/13952639/bed5502d-e7a2-4c28-959a-8c564d9491b5">

**Comment by gaoyifei1122** [comment]
any updates？I have the same problem

**Comment by M0hammadL** [comment]
@Koncopd  @chelseabright96 can you plz help

**Comment by chelseabright96** [comment]
Hi @gaoyifei1122, it seems the docs have not been updated. Thanks for brining this up! scArches works fine with python 3.9 and up. Please write if you come across any issues.
