### ISSUE TITLE
UnicodeEncodeError  in progress bar

### ISSUE THREAD

**Issue by Hrovatin** [theislab/scarches#25]
Occasionally I get the below error during training when I run the below code.
Version: scArches-0.1.2
```
network.train(adata,
              n_epochs=params['n_epochs'],
              batch_size=params['batch_size'], 
              condition_key='study_sample',
              save=True,
              retrain=True
             )

Traceback (most recent call last):
  File "code/diabetes_analysis/integration/scArches/1_run_ref_scArches_script.py", line 103, in <module>
    retrain=True
  File "/home/icb/karin.hrovatin/miniconda3/envs/py3.6-scarches/lib/python3.6/site-packages/scarches/models/cvae.py", line 749, in train
    verbose)
  File "/home/icb/karin.hrovatin/miniconda3/envs/py3.6-scarches/lib/python3.6/site-packages/scarches/models/scarches.py", line 496, in _train_on_batch
    print_progress(i, logs, n_epochs)
  File "/home/icb/karin.hrovatin/miniconda3/envs/py3.6-scarches/lib/python3.6/site-packages/scarches/models/_utils.py", line 125, in print_progress
    _print_progress_bar(epoch + 1, n_epochs, prefix='', suffix=message, decimals=1, length=20)
  File "/home/icb/karin.hrovatin/miniconda3/envs/py3.6-scarches/lib/python3.6/site-packages/scarches/models/_utils.py", line 132, in _print_progress_bar
    sys.stdout.write('\r%s |%s| %s%s %s' % (prefix, bar, percent, '%', suffix)),
UnicodeEncodeError: 'ascii' codec can't encode character '\u2588' in position 3: ordinal not in range(128)

**Comment by M0hammadL** [comment]
@Hrovatin  should be fixed now.
