### ISSUE TITLE
Multiple batches with trvae

### ISSUE THREAD

**Issue by ilyakorsunsky** [theislab/scarches#68]
I've noticed that when I run trvae to build my reference, I run into an error when I have more batches than latent dimensions (error below). When I increase the number of latent dimensions to be at least the number of batches, this goes away! I am curious if this behavior is an attribute of the underlying model or the implementation. It is important for me to integrate >200 batches and it seems impractical to use >200 latent dimensions to do so.

Thanks for your help and insight! 

In : trvae_full.train(
...:     n_epochs=trvae_epochs,
...:     alpha_epoch_anneal=trvae_epochs,
...:     early_stopping_kwargs=early_stopping_kwargs
...: )
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/models/trvae/trvae_model.py", line 282, in train
    self.trainer.train(n_epochs, lr, eps)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/trainers/trvae/trainer.py", line 167, in train
    self.on_iteration(batch_data)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/trainers/trvae/trainer.py", line 249, in on_iteration
    self.current_loss = loss = self.loss(**batch_data)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/trainers/trvae/unsupervised.py", line 62, in loss
    recon_loss, kl_loss, mmd_loss = self.model(**total_batch)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/models/trvae/trvae.py", line 179, in forward
    outputs = self.decoder(z1, batch)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/models/trvae/modules.py", line 188, in forward
    dec_latent = self.FirstL(z_cat)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/PHShome/ik936/anaconda3/envs/gpu/lib/python3.7/site-packages/scarches/models/trvae/modules.py", line 25, in forward
    expr, cond = torch.split(x, x.shape[1] - self.n_cond, dim=1)
ValueError: too many values to unpack (expected 2)

**Comment by Cottoneyejoe95** [comment]
Hi @ilyakorsunsky,

I cant reproduce this error. I tested it with 9 batches and latent dimension 2 and it works for me. Do you have the most recent build?

**Comment by ilyakorsunsky** [comment]
Hi @Cottoneyejoe95, Updating it to the latest build fixed it for me, thanks!
