### ISSUE TITLE
`concatenate` is not a static method in class `AnnData`

### ISSUE THREAD

**Issue by dustincys** [theislab/scarches#83]
Hi,  is it a bug here? it seems `concatenate` is not a static method in class `AnnData`

    Traceback (most recent call last):
      File "<stdin>", line 5, in <module>
      File "/home/ychu2/.local/lib/python3.7/site-packages/scarches/models/scgen/vaearith_model.py", line 224, in map_query_data
        integrated_query = new_model.batch_removal(reference_query_adata, batch_key = "reference_map", cell_label_key = "cell_type", return_late\
    nt = True)
      File "/home/ychu2/.local/lib/python3.7/site-packages/scarches/models/scgen/vaearith_model.py", line 147, in batch_removal
        corrected = self.model.batch_removal(adata, batch_key, cell_label_key, return_latent)
      File "/home/ychu2/.local/lib/python3.7/site-packages/scarches/models/scgen/vaearith.py", line 294, in batch_removal
        all_shared_ann = anndata.AnnData.concatenate(*shared_ct, batch_key="concat_batch", index_unique=None)
    TypeError: concatenate() missing 1 required positional argument: 'self'

**Comment by M0hammadL** [comment]
Hi, I think this is the problem with annData version, try to update it with latest version.
